// https://the-guild.dev/blog/nextra-4?utm_source=nextra.site&utm_campaign=blog_page&utm_content=blog_link

import { Footer, Layout, Navbar, Link } from 'nextra-theme-docs';
import { Banner } from 'nextra/components';
import { getPageMap } from 'nextra/page-map';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const pageMap = await getPageMap();

  const theme = 'dark';

  const banner = (
    <Banner dismissible={false}>
      🚧 This is WIP documentation{' '}
      <Link href="https://github.com/shuding/nextra/blob/main/docs/app/layout.tsx">nextra</Link>.
    </Banner>
  );
  const navbar = <Navbar logo={<b>Code Cracker 🥠</b>} logoLink="/" />;
  const footer = <Footer>MIT © Nextra.</Footer>;

  //

  return (
    <html lang="en" className={theme} style={{ colorScheme: theme }}>
      <body>
        <Layout
          darkMode={true}
          banner={banner}
          navbar={navbar}
          pageMap={pageMap}
          footer={footer}
          sidebar={{
            autoCollapse: true,
          }}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
